### ISSUE TITLE
Make Truss accessibility guide 1.0

### ISSUE THREAD

**Issue by xtine** [trussworks/accessibility#7]
PT IMPORTED STORY: https://www.pivotaltracker.com/story/show/171219462

**Description**
Create a Truss opinionated guide for accessibility work based on existing guides

**To do**
- [x] Review existing guides and pull out pieces we like
- [x] Organize our own guide
- [ ] Publish guide to this repo to be linked to or included in other Truss material (playbooks, proposals, etc.)

**Definition of done**
We have a published Truss accessibility guide that can be easily linked to from other Truss materials

**Comment by joshmfranklin** [comment]
Doc for outlining checklist:
https://docs.google.com/document/d/1zMS5-jOer8eigc2XwBbOd73UrCODRZJKxV3lPuHSdz8/edit
